#ifndef LORAHAM_DAEMON_VERSION_H
#define LORAHAM_DAEMON_VERSION_H

#define LORAHAM_DAEMON_NAME "loraham_daemon"
#define LORAHAM_DAEMON_VERSION "111"
#define LORAHAM_DAEMON_VERSION_TEXT LORAHAM_DAEMON_NAME " " LORAHAM_DAEMON_VERSION

#endif
